<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Candoumbe.MiscUtilities" Version="0.15.0"/>
    <PackageVersion Include="Candoumbe.Pipelines" Version="2.0.1"/>
    <PackageVersion Include="coverlet.msbuild" Version="10.0.1"/>
    <PackageVersion Include="FakeItEasy" Version="9.0.1"/>
    <PackageVersion Include="FluentAssertions" Version="7.2.2"/>
    <PackageVersion Include="FsCheck.XUnit" Version="3.3.3"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.17"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.17"/>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.0"/>
    <PackageVersion Include="Moq" Version="4.20.71"/>
    <PackageVersion Include="NodaTime" Version="3.3.3"/>
    <PackageVersion Include="NodaTime.Bogus" Version="3.0.2"/>
    <PackageVersion Include="RavenDB.Client" Version="6.2.17"/>
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0"/>
    <PackageVersion Include="TestContainers.RavenDb" Version="4.13.0"/>
    <PackageVersion Include="xunit.categories" Version="3.0.1"/>
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
  </ItemGroup>
  <Choose>
    <When Condition="'$(TargetFramework)' == 'netstandard2.0'">
      <ItemGroup>
        <PackageVersion Include="Optional" Version="4.0.0" Condition="'$(TargetFramework)' == 'netstandard2.0'"/>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageVersion Include="Ultimately" Version="3.0.0"/>
      </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup Condition="'$(IsTestProject)' == 'false'">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
  </ItemGroup>
</Project>