// <auto-generated />

#nullable disable

namespace Candoumbe.DataAccess.EFStore.UnitTests.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;

    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Acolyte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Acolytes");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcolyteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcolyteId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Acolyte", b =>
                {
                    b.HasOne("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Hero", null)
                        .WithMany("Acolytes")
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Weapon", b =>
                {
                    b.HasOne("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Acolyte", null)
                        .WithMany("Weapons")
                        .HasForeignKey("AcolyteId");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Acolyte", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("Candoumbe.DataAccess.EFStore.UnitTests.Entities.Hero", b =>
                {
                    b.Navigation("Acolytes");
                });
#pragma warning restore 612, 618
        }
    }
}
